### ISSUE TITLE
mp3 playback issue - Micro Python + Pico2

### ISSUE THREAD

**Issue by dsssssssss9** [FireMarshmellow/Dfrobot_Voice_Prompt_Module#2]
Hi

Great video - many thanks for getting me started with this device

On a Pico2 using you Micro Python code i can play the 2 demo tunes included on the device correctly

if i replace these with this sample ( counting from 1 to 10 ) it plays correctly also,,,,

[011_onetoten.mp3.zip](https://github.com/user-attachments/files/18118621/011_onetoten.mp3.zip)

However if i split this file into 10 separate samples the start of each sample  is cut off for a fraction of a second,,,

[onetoten.zip](https://github.com/user-attachments/files/18118637/onetoten.zip)

Any idea as to what i am doing wrong please?

**Comment by dsssssssss9** [comment]
@FireMarshmellow 

HI

any thoughts on this yet???

**Comment by FireMarshmellow** [comment]
The problem seems to be with the files themselves so however you divided them is the problem.

**Comment by dsssssssss9** [comment]
@FireMarshmellow 

Again i thank you for helping

i spilt a different  sample again with the same result but splitting a third time making sure that there is a fraction of a second ( at least 0.02 seconds it seems ) the samples play fine.

I may investigate further once i have got my current project with this device nearer the finish line

Regards
